import { useState } from "react";
import Layout from "../../components/common/Layout.jsx";
import AIToolLayout from "../../components/common/AIToolLayout.jsx";
import CreditBadge from "../../components/common/CreditBadge.jsx";
import LoadingSpinner from "../../components/common/LoadingSpinner.jsx";
import useCreditStore from "../../store/creditStore.js";
import api from "../../api/axios.js";
import { Download, Image } from "lucide-react";


const ImageGenerator = () => {
  const [imageLoading, setImageLoading] = useState(false);
  const [prompt, setPrompt] = useState("");
  const [size, setSize] = useState("1024x1024");
  const [result, setResult] = useState(null);
  const [meta, setMeta] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const { fetchBalance } = useCreditStore();

  const sizes = ["512x512", "1024x1024", "1024x576", "576x1024"];

  const handleSubmit = async () => {
    if (!prompt.trim()) return;
    setLoading(true);
    setError(null);
    setResult(null);

    try {
      const [width, height] = size.split("x").map(Number);
      const { data } = await api.post("/image/generate", { prompt, width, height });
      setResult(data.data.imageUrl);
      setImageLoading(true); // image URL received but image not rendered yet
      setMeta({
        creditsUsed: data.data.creditsUsed,
        remainingCredits: data.data.remainingCredits,
      });
      fetchBalance();
    } catch (err) {
      setError(err.response?.data?.message || "Something went wrong.");
    } finally {
      setLoading(false); // button loading done
    }
  }
  return (
    <Layout>
      <AIToolLayout
        title="Image Generator"
        description="Generate images from text prompts."
        cost="10 credits"
      >
        <div className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-gray-300 mb-1.5">
              Describe your image
            </label>
            <textarea
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              placeholder="e.g. A futuristic city at night with neon lights reflecting on wet streets"
              rows={3}
              className="w-full px-3 py-2.5 bg-zinc-900 border border-zinc-800 rounded-lg text-white placeholder:text-zinc-600 focus:outline-none focus:ring-1 focus:ring-zinc-600 text-sm resize-none transition-colors"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-300 mb-1.5">Size</label>
            <div className="flex gap-2 flex-wrap">
              {sizes.map((s) => (
                <button
                  key={s}
                  onClick={() => setSize(s)}
                  className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-colors ${
                    size === s
                      ? " bg-white text-black"
                      : "bg-zinc-900 text-zinc-400 hover:text-white border border-zinc-800 transition-colors"
                  }`}
                >
                  {s}
                </button>
              ))}
            </div>
          </div>

          <button
            onClick={handleSubmit}
            disabled={loading || !prompt.trim()}
            className="w-full py-2.5 bg-white hover:bg-zinc-200 disabled:opacity-40 disabled:cursor-not-allowed text-black font-medium rounded-lg transition-colors flex items-center justify-center gap-2 text-sm"
          >
            {loading ? <LoadingSpinner size="sm" /> : "Generate Image"}
          </button>

          {loading && (
            <p className="text-center text-xs text-gray-400">
              Generating your image, this may take a few seconds...
            </p>
          )}

          {error && (
            <div className="p-3 bg-red-500/10 border border-red-500/20 rounded-lg">
              <p className="text-red-400 text-sm">{error}</p>
            </div>
          )}

          {result && (
            <div className="rounded-xl border border-zinc-800 overflow-hidden bg-zinc-900">
              {/* Skeleton shown while image loads */}
              {imageLoading && (
                <div className="flex flex-col items-center justify-center gap-3 p-12 bg-zinc-900">
                  <LoadingSpinner size="lg" text="Rendering image..." />
                  <p className="text-xs text-zinc-600 text-center max-w-xs">
                    Image is being generated by Pollinations AI. This may take 10–30 seconds.
                  </p>
                </div>
              )}

              <img
                src={result}
                alt={prompt}
                className={`w-full object-cover transition-opacity duration-500 ${
                  imageLoading ? "hidden" : "block opacity-100"
                }`}
                onLoad={() => setImageLoading(false)}
                onError={() => {
                  setImageLoading(false);
                  setError("Image failed to load. The service may be busy — please try again.");
                }}
              />

              {!imageLoading && (
                <div className="p-3 flex items-center justify-between border-t border-zinc-800">
                  <p className="text-xs text-zinc-500 truncate flex-1">{prompt}</p>
                  <a
                    href={result}
                    download="nexora-image.jpg"
                    target="_blank"
                    rel="noreferrer"
                    className="ml-3 flex items-center gap-1.5 text-xs text-zinc-400 hover:text-white transition-colors flex-shrink-0"
                  >
                    <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                      <path strokeLinecap="round" strokeLinejoin="round" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                    </svg>
                    Download
                  </a>
                </div>
              )}
            </div>
          )}

          <CreditBadge {...meta} />
        </div>
      </AIToolLayout>
    </Layout>
  );
};
export default ImageGenerator;