export const CREDIT_COSTS = {
  // Text to Text
  CHAT: 2,
  CONTENT_GENERATION: 5,
  SUMMARIZATION: 3,
  TRANSLATION: 3,
  GRAMMAR_CHECK: 1,
  CODE_EXPLANATION: 3,

  // Coding Tasks
  CODE_GENERATION: 5,
  CODE_DEBUGGING: 4,
  CODE_REVIEW: 4,
  CODE_REFACTORING: 4,
  CODE_DOCUMENTATION: 3,
  UNIT_TEST_GENERATION: 4,
  CODE_CONVERSION: 4,    // e.g. Python to JavaScript

  // Text to Image
  IMAGE_GENERATION: 10,
  LOGO_CREATION: 15,
  SOCIAL_MEDIA_GRAPHIC: 10,

  // Image to Text
  OCR: 4,
  IMAGE_DESCRIPTION: 4,
  OBJECT_DETECTION: 5,
  HANDWRITING_RECOGNITION: 5,
  DOCUMENT_SCANNING: 6,

  // Document Analysis
  PDF_EXTRACTION: 5,
  DOCUMENT_QA: 5,
  KEY_POINTS_EXTRACTION: 4,
  DOCUMENT_SUMMARIZATION: 5,
};
export const SUBSCRIPTION_CREDITS = {
  free: 100,
  pro: 1000,
  enterprise: 10000,
};

